# Generated by Django 4.2.7 on 2025-08-25 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('original_file', models.FileField(upload_to='music/original/')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='music/converted/')),
                ('original_extension', models.CharField(max_length=10)),
                ('target_extension', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('ogg', 'OGG'), ('flac', 'FLAC'), ('m4a', 'M4A'), ('aac', 'AAC')], default='mp3', max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Music Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
