# Generated by Django 5.2.5 on 2025-08-25 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('extension', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('ogg', 'OGG'), ('flac', 'FLAC'), ('m4a', 'M4A')], max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Music Files',
            },
        ),
    ]
